//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety_for_Windows.Src.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class FRIEND_REQUEST
    {
        [DataMember(Order = 1)]
        public int Friend_RequestID { get; set; }
        [DataMember(Order = 2)]
        public int Accepted { get; set; }
        [DataMember(Order = 3)]
        public int UserID { get; set; }
        [DataMember(Order = 4)]
        public Nullable<int> FriendID { get; set; }

        [DataMember(Order = 5)]
        public virtual USER USER { get; set; }
        [DataMember(Order = 6)]
        public virtual USER USER1 { get; set; }
    }
}
