//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety_for_Windows.Src.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class ORGANIZATION
    {
        public ORGANIZATION()
        {
            this.ADVERTs = new List<ADVERT>();
        }

        [DataMember(Order = 1)]
        public int OrganizationID { get; set; }
        [DataMember(Order = 2)]
        public string Name { get; set; }
        [DataMember(Order = 3)]
        public string Description { get; set; }
        [DataMember(Order = 4)]
        public string Email { get; set; }
        [DataMember(Order = 5)]
        public string Password { get; set; }
        [DataMember(Order = 6)]
        public string ImageURL { get; set; }

        [DataMember(Order = 7)]
        public virtual List<ADVERT> ADVERTs { get; set; }
    }
}
