//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety_for_Windows.Src.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class PET
    {
        public PET()
        {
            this.GALLERies = new List<GALLERY>();
            this.LOSTs = new List<LOST>();
        }

        [DataMember(Order = 1)]
        public int PetID { get; set; }
        [DataMember(Order = 2)]
        public string Name { get; set; }
        [DataMember(Order = 3)]
        public string Breed { get; set; }
        [DataMember(Order = 4)]
        public string Sex { get; set; }
        [DataMember(Order = 5)]
        public string Type { get; set; }
        [DataMember(Order = 6)]
        public string Biography { get; set; }
        [DataMember(Order = 7)]
        public string Age { get; set; }
        [DataMember(Order = 8)]
        public int UserID { get; set; }
        [DataMember(Order = 9)]
        public Nullable<int> GalleryID { get; set; }
        [DataMember(Order = 10)]
        public string ProfileImageURL { get; set; }
        [DataMember(Order = 11)]
        public Nullable<System.DateTime> DateTimeCreated { get; set; }


        [DataMember(Order = 12)]
        public virtual List<GALLERY> GALLERies { get; set; }
        [DataMember(Order = 13)]
        public virtual GALLERY GALLERY { get; set; }
        [DataMember(Order = 14)]
        public virtual List<LOST> LOSTs { get; set; }
        [DataMember(Order = 15)]
        public virtual USER USER { get; set; }
    }

}
