//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSociety_for_Windows.Src.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class USER
    {
        public USER()
        {
            this.ATTENDEEs = new List<ATTENDEE>();
            this.EVENTs = new List<EVENT>();
            this.FRIEND_LIST = new List<FRIEND_LIST>();
            this.FRIEND_LIST1 = new List<FRIEND_LIST>();
            this.FRIEND_REQUEST = new List<FRIEND_REQUEST>();
            this.FRIEND_REQUEST1 = new List<FRIEND_REQUEST>();
            this.GALLERies = new List<GALLERY>();
            this.LOCATIONs = new List<LOCATION>();
            this.LOSTs = new List<LOST>();
            this.PETs = new List<PET>();
            this.REVIEWs = new List<REVIEW>();
            this.STRAYs = new List<STRAY>();
        }

        [DataMember(Order = 1)]
        public int UserID { get; set; }
        [DataMember(Order = 2)]
        public string Name { get; set; }
        [DataMember(Order = 3)]
        public string Email { get; set; }
        [DataMember(Order = 4)]
        public string Birthday { get; set; }
        [DataMember(Order = 5)]
        public string Password { get; set; }
        [DataMember(Order = 6)]
        public string Address { get; set; }
        [DataMember(Order = 7)]
        public string Biography { get; set; }
        [DataMember(Order = 8)]
        public string Privicy { get; set; }
        [DataMember(Order = 9)]
        public string Sex { get; set; }
        [DataMember(Order = 10)]
        public string Contact { get; set; }
        [DataMember(Order = 11)]
        public string Credibility { get; set; }
        [DataMember(Order = 12)]
        public Nullable<double> X { get; set; }
        [DataMember(Order = 13)]
        public Nullable<double> Y { get; set; }
        [DataMember(Order = 14)]
        public string ProfileImageURL { get; set; }


        [DataMember(Order = 15)]
        public virtual List<ATTENDEE> ATTENDEEs { get; set; }
        [DataMember(Order = 16)]
        public virtual List<EVENT> EVENTs { get; set; }
        [DataMember(Order = 17)]
        public virtual List<FRIEND_LIST> FRIEND_LIST { get; set; }
        [DataMember(Order = 18)]
        public virtual List<FRIEND_LIST> FRIEND_LIST1 { get; set; }
        [DataMember(Order = 19)]
        public virtual List<FRIEND_REQUEST> FRIEND_REQUEST { get; set; }
        [DataMember(Order = 20)]
        public virtual List<FRIEND_REQUEST> FRIEND_REQUEST1 { get; set; }
        [DataMember(Order = 21)]
        public virtual List<GALLERY> GALLERies { get; set; }
        [DataMember(Order = 22)]
        public virtual List<LOCATION> LOCATIONs { get; set; }
        [DataMember(Order = 23)]
        public virtual List<LOST> LOSTs { get; set; }
        [DataMember(Order = 24)]
        public virtual List<PET> PETs { get; set; }
        [DataMember(Order = 25)]
        public virtual List<REVIEW> REVIEWs { get; set; }
        [DataMember(Order = 26)]
        public virtual List<STRAY> STRAYs { get; set; }
    }

}
